"use client";
import { useState } from "react";
import type { Job, Verification } from "@/lib/types";
import { date, label } from "@/lib/client";
import { Icon } from "./icons";
export const tabs = ["Overview", "Architecture", "Findings", "Plan", "Activity", "Terminal", "Diff", "Documentation"] as const;
export type Tab = typeof tabs[number];
export function EmptyState({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="empty-state"><div className="empty-art" aria-hidden="true"><span/><Icon name="folder" size={29}/><span/></div><h3>{title}</h3><p>{children}</p></div>;
}
export function Download({ job, kind, children }: { job: Job; kind: "report" | "report.html" | "diff"; children: React.ReactNode }) {
  return <a className="secondary-button compact" href={`/api/jobs/${job.id}/${kind}`} download><Icon name="download" size={14}/>{children}</a>;
}
function VerificationCard({ title, result }: { title: string; result: Verification | null }) {
  return <div className="verification-card"><span>{title}</span><strong>{result ? label(result.status) : "Not run"}</strong>{result && <small>{result.tests !== null ? `${result.tests} tests · ${result.failures ?? 0} failures · ${result.skipped ?? 0} skipped` : "No test counts reported"}{result.durationMs > 0 ? ` · ${(result.durationMs / 1000).toFixed(1)}s` : ""}</small>}</div>;
}
function DiffPanel({ job }: { job: Job }) {
  const [file, setFile] = useState("");
  const chunks = job.diff.split(/(?=^diff --git )/m).filter(Boolean);
  const files = chunks.map(chunk => ({ path: chunk.match(/^\+\+\+ "?b\/(.+?)"?$/m)?.[1] || chunk.match(/^--- "?a\/(.+?)"?$/m)?.[1] || "Patch", content: chunk }));
  const actualFile = files.some(item => item.path === file) ? file : "";
  const content = actualFile ? files.find(item => item.path === actualFile)?.content || "" : job.diff;
  return <div className="panel-body"><div className="section-toolbar"><div><h3>Review the changes</h3><p>{job.changeSummary || "No change summary recorded."}</p></div>{job.diff && <Download job={job} kind="diff">Download patch</Download>}</div>{job.diff ? <><label className="select-label" htmlFor="diff-file">Show file<select id="diff-file" value={actualFile} onChange={event => setFile(event.target.value)}><option value="">All changed files</option>{files.map((item, index) => <option key={index} value={item.path}>{item.path}</option>)}</select></label><pre className="code-output diff-output">{content.split("\n").map((line, i) => <span key={i} className={line.startsWith("+") && !line.startsWith("+++") ? "added" : line.startsWith("-") && !line.startsWith("---") ? "removed" : line.startsWith("@@") ? "hunk" : ""}>{line}{"\n"}</span>)}</pre></> : <EmptyState title="No code changes recorded">Any edits will appear here as a reviewable patch. The report still documents analysis and checks.</EmptyState>}</div>;
}
export function JobPanel({ job, tab }: { job: Job; tab: Tab }) {
  const analysis = job.analysis;
  if (tab === "Overview") return <div className="panel-body"><div className="section-toolbar"><div><h3>Repository overview</h3><p>{job.objective || "Doctor Scan · inspect the repository and record evidence."}</p></div><span className="tag">{job.mode}</span></div>{analysis ? <><div className="fact-grid">{[["Language", analysis.language], ["Java", analysis.javaVersion], ["Build tool", analysis.buildTool], ["Spring Boot", analysis.springBootVersion]].map(([key, value]) => <div key={key}><span>{key}</span><strong>{value || "Not detected"}</strong></div>)}</div>{job.sourceRevision && <p className="revision">Source revision <code>{job.sourceRevision}</code>{job.sourceDefaultBranch ? ` · ${job.sourceDefaultBranch}` : ""}</p>}<h4>What the analysis found</h4>{analysis.observations.length ? <ul className="evidence-list">{analysis.observations.map((text, index) => <li key={index}>{text}</li>)}</ul> : <p className="muted">No repository observations were recorded.</p>}<div className="two-columns"><div><h4>Modules</h4><FileList files={analysis.modules}/></div><div><h4>Important files</h4><FileList files={analysis.importantFiles}/></div></div></> : <p className="muted">Repository detection has not produced results yet.</p>}<h4>Main changes</h4><p className="change-summary">{job.changeSummary || "No code changes have been made."}</p><h4>Verification</h4><div className="verification-grid"><VerificationCard title="Baseline build" result={job.baselineBuild}/><VerificationCard title="Baseline tests" result={job.baselineTests}/><VerificationCard title="Final build" result={job.finalBuild}/><VerificationCard title="Final tests" result={job.finalTests}/></div>{job.concerns.length > 0 && <><h4>Open concerns</h4><ul className="evidence-list">{job.concerns.map((concern, index) => <li key={index}>{concern}</li>)}</ul></>}</div>;
  if (tab === "Architecture") {
    if (!analysis) return <EmptyState title="Architecture awaits analysis">Detected modules, Java symbols, and source-level relationships will appear here.</EmptyState>;
    const layers = [...new Set(analysis.symbols.map(symbol => symbol.layer || "Other"))];
    return <div className="panel-body"><h3>Detected architecture</h3><p className="muted">Source-level relationships inferred from the code. This is a static overview, not a runtime trace.</p><div className="architecture-map">{layers.map(layer => <div key={layer}><span className="mono">{layer}</span><strong>{analysis.symbols.filter(symbol => (symbol.layer || "Other") === layer).length} symbols</strong></div>)}</div>{analysis.symbols.length ? <div className="symbol-list">{analysis.symbols.map((symbol, index) => <details key={`${symbol.file}:${index}`}><summary><strong>{symbol.name}</strong><span className="tag">{symbol.layer || symbol.kind}</span><code>{symbol.file}:{symbol.line}</code></summary><div><p><strong>Package</strong> {symbol.packageName || "Default package"}</p><p><strong>Annotations</strong> {symbol.annotations.join(", ") || "None detected"}</p><p><strong>Dependencies</strong> {symbol.dependencies.join(", ") || "None detected"}</p></div></details>)}</div> : <p className="muted">No Java symbols detected.</p>}</div>;
  }
  if (tab === "Findings") return <div className="panel-body"><h3>{analysis ? `${analysis.findings.length} recorded findings` : "Findings"}</h3><p className="muted">Prioritized evidence and suggestions from this run.</p>{analysis?.findings.map((finding, index) => <article className="finding" key={index}><div><span className={`severity ${finding.severity.toLowerCase()}`}>{finding.severity}</span><span className="tag">{finding.type}</span><h4>{finding.title}</h4></div><code>{finding.file}{finding.line ? `:${finding.line}` : ""}</code><p>{finding.explanation}</p>{finding.evidence && <pre className="code-output">{finding.evidence}</pre>}<p className="suggestion">{finding.suggestion}</p></article>)}{!analysis?.findings.length && <EmptyState title={analysis ? "No findings recorded" : "No findings yet"}>{analysis ? "A static scan does not establish that the repository is free of defects. Review the report for the analysis scope and limits." : "Evidence-backed findings will appear after repository analysis."}</EmptyState>}</div>;
  if (tab === "Plan") return job.plan ? <div className="panel-body"><div className="section-toolbar"><h3>Proposed repair plan</h3><span className="tag">{job.status === "AWAITING_APPROVAL" ? "Awaiting your approval" : "Recorded plan"}</span></div><p>{job.plan.summary}</p><ol className="plan-steps">{job.plan.steps.map((step, index) => <li key={index}>{step}</li>)}</ol><h4>Files in scope</h4><FileList files={job.plan.files}/><h4>Risks to review</h4>{job.plan.risks.length ? <ul className="evidence-list">{job.plan.risks.map((risk, index) => <li key={index}>{risk}</li>)}</ul> : <p className="muted">No specific risks were recorded in the plan.</p>}<p className="small-note">Approval authorizes sandbox edits and verification for this exact plan. Publishing has a separate confirmation.</p></div> : <EmptyState title="No repair plan recorded">A plan requires a configured Groq provider. Doctor Scan can still inspect a repository without a model key.</EmptyState>;
  if (tab === "Activity") return job.events.length ? <div className="event-list">{job.events.map(event => <article key={event.sequence}><span className={`event-dot ${event.status.toLowerCase()}`}/><div><div className="event-title"><strong>{event.tool || event.stage}</strong><time>{date(event.timestamp)}</time></div><p>{event.message}</p><small>{event.stage} · {label(event.status)}{event.durationMs > 0 ? ` · ${(event.durationMs / 1000).toFixed(1)}s` : ""}</small></div></article>)}</div> : <EmptyState title="Waiting for the first event">Actual tool actions and their results will appear here.</EmptyState>;
  if (tab === "Terminal") {
    const commands = [["Baseline build", job.baselineBuild], ["Baseline tests", job.baselineTests], ["Final build", job.finalBuild], ["Final tests", job.finalTests]] as const;
    return <div className="panel-body"><h3>Actual execution output</h3><p className="muted">Commands that did not run are explicitly identified. Repository code requires the sandbox.</p>{job.terminal && <pre className="code-output terminal-output">{job.terminal}</pre>}{commands.map(([name, result]) => <details className="command-output" key={name} open={!!result}><summary><strong>{name}</strong><span>{result ? label(result.status) : "Not run"}</span></summary>{result && <pre className="code-output">{result.output || "No command output was captured."}</pre>}</details>)}</div>;
  }
  if (tab === "Diff") return <DiffPanel job={job}/>;
  return <div className="panel-body"><div className="section-toolbar"><div><span className="eyebrow">THE DOCTOR REPORT</span><h3>What changed, and why.</h3><p>Repository context, main changes, file explanations, and actual verification.</p></div>{job.reportMarkdown && <div className="download-actions"><Download job={job} kind="report">Markdown</Download><Download job={job} kind="report.html">HTML / print</Download></div>}</div><div className="main-change"><span className="mono">MAIN CHANGE</span><p>{job.changeSummary || "No code changes have been made."}</p></div>{job.changes.length > 0 && <div className="change-list">{job.changes.map((change, index) => <article key={index}><div><code>{change.file}</code><span className="diff-stat"><i>+{change.additions}</i> −{change.deletions}</span></div><h4>{change.summary}</h4><p>{change.reason}</p></article>)}</div>}{job.reportMarkdown ? <pre className="report-output">{job.reportMarkdown}</pre> : <EmptyState title="The report is being prepared">A downloadable record will be available when the backend has generated it, including on runs with no changes.</EmptyState>}</div>;
}
function FileList({ files }: { files: string[] }) { return files.length ? <ul className="file-list">{files.map((file, index) => <li key={index}><Icon name="folder" size={13}/><code>{file}</code></li>)}</ul> : <p className="muted">None recorded.</p>; }
